### ISSUE TITLE
Interazione simulazione temperatura alta - lock temperatura

### ISSUE THREAD

**Issue by lorenzoverde** [faaber/Galleria-Java#5]
@faaber dovresti dare un'occhiata all'uso della simulazione temperatura con e senza lock, credo che ci sia qualcosa che non vada se il lock è attivo e provi a simulare la temperatura bassa, ma non solo.

**Comment by faaber** [comment]
Descrivi il flusso degli eventi che porta al bug e descrivi il bug.

**Comment by lorenzoverde** [comment]
1. avvia il programma ed effettua il login come operatore
2. apri la finestra di manutenzione
3. attiva il lock della temperatura
4. simula la temperatura alta causando l'attivazione della PAI
Adesso, a meno che questo non sia il comportamento atteso, simulare la temperatura bassa con il lock attivo fa passare lo stato da rosso a verde

**Comment by faaber** [comment]
Questo è il comportamento atteso. Ho fatto un cambio: prima il rettangolo di stato aveva un duplice significato: quando non c'era il lock indicava se la temperatura era alta/bassa, mentre quando c'era il lock indicava se la procedura antincendio era attivata/disattivata. Adesso, invece, sia quando c'è il lock sia quando non c'è, il rettangolo di stato indica se la temperatura è alta/bassa.

Ho modificato la logica della classe in questo modo:
- la variabile "temperaturaAlta" indica se è stata rilevata una temperatura alta/bassa. Il cambio di valore non avviene nell'istante di ricezione dell'input di temperatura alta/bassa, ma avviene quando quest'input non viene seguito da uno opposto per un numero di millisecondi pari a "ritardoAttivazione";
- la variabile "PAIAttiva" è incaricata di indicare lo stato di attivazione/disattivazione della procedura antincendio. Ora è questa la variabile a cui va collegata la segnalazione della PAI attiva nel tab "PAI".

Avrei dovuto avvisarti del cambio della logica della classe, scusa.
