### ISSUE TITLE
interfaccia login tagliata

### ISSUE THREAD

**Issue by MN2194** [faaber/Galleria-Java#6]
All'apertura dell'interfaccia login essa risulta tagliata inferiormente. Dopo alcune modifiche alla risoluzione dello schermo il problema persiste.

**Comment by alessandro12p** [comment]
A me non presenta problemi. Le cause del tuo problema potrebbero essere due:
- non stai lavorando su una versione aggiornata;
- non stai lavorando sul branch development.

Posta un'immagine della tua schermata di login.

**Comment by MN2194** [comment]
![immaginelogin](https://cloud.githubusercontent.com/assets/24355823/21319009/c5eae640-c60b-11e6-9d05-52594600dea1.png)

**Comment by MN2194** [comment]
Stavo usando la Master che non era aggiornata, adesso ho scaricato la development e l'interfaccia non cambia

**Comment by alessandro12p** [comment]
Questa è l'interfaccia di login che appare a me:
![img](https://cloud.githubusercontent.com/assets/18363519/21319116/31c4bdf0-c60c-11e6-812f-23055fac9c8a.jpg)

**Comment by alessandro12p** [comment]
Noto che le proporzioni sono diverse. Quali versioni di NetBeans e di Java SE stai utilizzando? Se stai utilizzando NetBeans precedente a 8.2 e Java SE precedente a 8u111, un aggiornamento può risolvere il problema.

**Comment by MN2194** [comment]
Ho entrambe le versioni installate e la grafica è la medesima, è un problema che persiste solo sul mio pc e non ne comprendo la causa

**Comment by alessandro12p** [comment]
Questo problema si presenta sia sul tuo computer fisso che sul tuo portatile?

**Comment by lorenzoverde** [comment]
A me neanche crea problemi, comunque credo di sapere eventualmente quale potrebbe essere la causa: nell'fxml di quella schermata ci sono degli elementi grafici che in realtà non sono utilizzati, quando ho tempo vedo di eliminarli e vediamo se si aggiusta, tanto non è una cosa urgente.

Edit: mi correggo, era la schermata di manutenzione ad avere quegli elementi.
