### ISSUE TITLE
Interfaccia PAI Operatore/Controllore

### ISSUE THREAD

**Issue by MN2194** [faaber/Galleria-Java#7]
Facendo l'accesso come "operatore", attivando "templock" e simulando la temperatura alta la procedura P.A.I non si attiva e l'interfaccia rimane di colore verde riportando la scritta "P.A.I NON ATTIVA"

**Comment by alessandro12p** [comment]
Ho seguìto il tuo stesso flusso di eventi, e la PAI si è attivata correttamente. Anche in questo caso la causa del tuo problema può essere che stai lavorando su una versione non aggiornata, oppure non stai lavorando sul branch development.
